name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Run docker-compose
        run: |
          docker compose up --build --exit-code-from clear