name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Similar to docker-compose.yml but not the same, 🤷‍♂️
    services:
      postgres:
        image: postgres:11.6-alpine
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Create databases
        run: |
          PGPASSWORD=password psql -U postgres -tc "DROP DATABASE IF EXISTS clear_spec;"
          PGPASSWORD=password psql -U postgres -tc "CREATE DATABASE clear_spec;
          PGPASSWORD=password psql -U postgres -tc "DROP DATABASE IF EXISTS clear_secondary_spec;"
          PGPASSWORD=password psql -U postgres -tc "CREATE DATABASE clear_secondary_spec;"
          PGPASSWORD=password psql -U postgres -tc "CREATE TABLE clear_secondary_spec.models_post_stats (id serial PRIMARY KEY, post_id INTEGER);"

      - uses: actions/checkout@v2
      - uses: oprypin/install-crystal@v1
        with:
          crystal: 1.0.0
      - run: shards install --ignore-crystal-version
      - run: ENV=ci DB_HOST=postgres crystal spec -Dquiet --warnings=all